### ISSUE TITLE
Bundler could not find compatible versions for gem "railties"

### ISSUE THREAD

**Issue by reckerswartz** [sass/sassc-rails#124]
This issue is on Rails master branch.
ticket reference https://github.com/rails/rails/issues/36112
sass-rails railties version lies between (>= 4.0.0, < 5.0) due to sassc-rails
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    rails was resolved to 6.1.0.alpha, which depends on
      railties (= 6.1.0.alpha)

    sass-rails (~> 5) was resolved to 5.0.4, which depends on
      railties (>= 4.0.0, < 5.0)

    web-console was resolved to 4.0.0, which depends on
      railties (>= 6.0.0.a)

    webpacker was resolved to 4.0.2, which depends on
      railties (>= 4.2)

**Comment by vimutter** [comment]
Hi 
It seems that issue is for old gem, this repo is for sassc-rails. 
Anyway, when you check gemspec on master here (since you're using alpha rails, I guess we need to use master here), you may see that there is no ceiling requirement on railties.

Can you please check gem name and version? You can also send your Gemfile.
